# -*- coding: utf-8 -*-
"""untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/imsrinanda/7c4dc4ff23c8f06578d87f3e91537551/untitled10.ipynb
"""

#Question 1
bank = open("/content/bank.csv","r")
bank_dataset = bank.readlines()
bank_list = []
for line in bank_dataset:
  ds = line.strip().split(";")
  bank_list.append(ds)
def view_dataset(bank_list):
  for i in bank_list:
    print(i)

# Question 2
def view_header(bank_dataset):
  header = bank_dataset[0].strip().split(";")
  print(header)
view_header(bank_dataset)

#Question 3
def count_married_emp(bank_list):
  detailed_sep = [i for i in bank_list]

  a = 0
  for i in detailed_sep:
    for j in i:
      if j == '"married"':
        a += 1
  print(a)
count_married_emp(bank_list)

#Question 4
ag = []
for i in bank_list:
    ag.append(i[0])
ag = ag[1:]
ages = []
for i in ag:
  j = int(i)
  ages.append(j)
print(ages)

def prepare_age_histogram(ages):
    age_ranges = {
        "0-10": 0,
        "11-20": 0,
        "21-30": 0,
        "31-40": 0,
        "41-50": 0,
        "51-60": 0,
        "61-70": 0,
        "71-80": 0,
        "81-90": 0,
        "91-100": 0,
        "101+": 0
    }

    for age in ages:
        if age <= 10:
            age_ranges["0-10"] += 1
        elif age <= 20:
            age_ranges["11-20"] += 1
        elif age <= 30:
            age_ranges["21-30"] += 1
        elif age <= 40:
            age_ranges["31-40"] += 1
        elif age <= 50:
            age_ranges["41-50"] += 1
        elif age <= 60:
            age_ranges["51-60"] += 1
        elif age <= 70:
            age_ranges["61-70"] += 1
        elif age <= 80:
            age_ranges["71-80"] += 1
        elif age <= 90:
            age_ranges["81-90"] += 1
        elif age <= 100:
            age_ranges["91-100"] += 1
        else:
            age_ranges["101+"] += 1

    print("Histogram for age:")
    for age_range, count in age_ranges.items():
        print(f"{age_range}: {'*' * count}")
prepare_age_histogram(ages)

menu = input('''
Hello!
Choose what you want to do.
1) View the dataset.
2) View the header.
3) View the count of married people.
4) View the histogram.
5) Exit.
Only enter 1 (or) 2 (or) 3 (or) 4 (or) 5.
''')

if menu == "1":
  view_dataset(bank_list)
elif menu == "2":
  view_header(bank_dataset)
elif menu == "3":
  count_married_emp(bank_list)
elif menu == "4":
  prepare_age_histogram(ages)
elif menu == "5":
  print("Successfully exited!")
else:
  print("Invalid option! Run the code again.")